/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
    "./src/app/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      keyframes: {
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(32px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'fade-in-up': 'fade-in-up 0.8s cubic-bezier(0.4,0,0.2,1) forwards',
      },
      fontFamily: {
        'display-xl': ['Noto Serif', 'serif'],
        'headline-lg': ['Noto Serif', 'serif'],
        'headline-md': ['Noto Serif', 'serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'serif': ['Noto Serif', 'serif'],
        'sans': ['Plus Jakarta Sans', 'sans-serif'],
        'material-symbols': ['Material Symbols Outlined'],
      },
      colors: {
        'primary': '#005f48',
        'primary-container': '#007a5e',
        'on-primary': '#ffffff',
        'on-primary-container': '#a4ffdd',
        'secondary': '#bb001e',
        'secondary-container': '#e12531',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#fffbff',
        'tertiary': '#715c00',
        'tertiary-container': '#cba800',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#4d3e00',
        'surface': '#f6faf6',
        'surface-container': '#eaefeb',
        'surface-container-low': '#f0f5f0',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e5e9e5',
        'surface-container-highest': '#dfe4df',
        'surface-variant': '#dfe4df',
        'surface-bright': '#f6faf6',
        'surface-dim': '#d7dbd7',
        'background': '#f6faf6',
        'on-background': '#181d1a',
        'on-surface': '#181d1a',
        'on-surface-variant': '#3e4944',
        'outline': '#6e7a74',
        'outline-variant': '#bdc9c2',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-surface': '#2c322f',
        'inverse-on-surface': '#edf2ee',
        'inverse-primary': '#79d8b7',
        'primary-fixed': '#95f5d2',
        'primary-fixed-dim': '#79d8b7',
        'on-primary-fixed': '#002117',
        'on-primary-fixed-variant': '#00513d',
        'secondary-fixed': '#ffdad7',
        'secondary-fixed-dim': '#ffb3ae',
        'on-secondary-fixed': '#410004',
        'on-secondary-fixed-variant': '#930015',
        'tertiary-fixed': '#ffe17b',
        'tertiary-fixed-dim': '#ecc300',
        'on-tertiary-fixed': '#231b00',
        'on-tertiary-fixed-variant': '#554500',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'base-unit': '8px',
        'section-padding': '80px',
        'gutter': '24px',
        'margin-mobile': '16px',
        'container-max-width': '1280px',
        'margin-desktop': '64px',
      },
      fontSize: {
        'display-xl': ['64px', { lineHeight: '1.1', fontWeight: '700' }],
        'headline-lg': ['40px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['14px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
